[package]
name = "bevity-settings"
version = "0.1.0"
edition = "2021"
readme = false

[lib]
path = "settings.rs"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
bevy.workspace = true
bevity-yaml = { path = "../yaml" }