[package]
name = "bevity-primitives"
version = "0.1.0"
edition = "2021"
readme = false

[lib]
path = "primitives.rs"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
bevy.workspace = true