[package]
name = "bevity-builder"
version = "0.1.0"
edition = "2021"
readme = false

[lib]
path = "builder.rs"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
syn = { version = "2", features = ["full"] }
genco = "0.17.5"