[package]
name = "bevity-generator"
version = "0.1.0"
edition = "2021"
readme = false

[lib]
path = "generator.rs"
proc-macro = true

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true