[package]
name = "bevity-yaml"
version = "0.1.0"
edition = "2021"
readme = false

[lib]
path = "yaml.rs"

[dependencies]
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_yaml.workspace = true